import { normalizeDebateOutput } from "./debate-terminology";
import {
  asAdvisoryPanelRun,
  asConsensusRun,
  asDebateRun,
  modeLabels,
  recordMode,
  type PolyviseRecord,
} from "./run-record";

export function isSimulatedRun(record: PolyviseRecord): boolean {
  return Boolean(
    record.latestRun?.modelSnapshots.some(
      (snapshot) => snapshot.model === "deterministic-template",
    ),
  );
}

/** Portable text from the stored result; never invent a missing verdict. */
export function runBrief(record: PolyviseRecord): string {
  record = normalizeDebateOutput(record);
  const lines = [
    `# ${record.resolution || record.subject}`,
    "",
    `Mode: ${modeLabels[recordMode(record)]}`,
    `Status: ${record.status}`,
    `Run: ${record.id}`,
    `Created: ${record.createdAt}`,
    "",
  ];
  if (isSimulatedRun(record))
    lines.push(
      "Simulated development run. Findings and sources are test responses, not live research.",
      "",
    );
  if (record.context) lines.push("## Context", record.context, "");
  const run = record.latestRun;
  if (!run) return [...lines, "No result is available yet."].join("\n");
  const list = (title: string, values: string[]) => {
    if (values.length)
      lines.push(`## ${title}`, ...values.map((value) => `- ${value}`), "");
  };
  const debate = asDebateRun(run);
  const consensus = asConsensusRun(run);
  const panel = asAdvisoryPanelRun(run);
  if (debate?.summary) {
    lines.push(
      "## Verdict",
      debate.summary.headline,
      "",
      debate.summary.recommendation,
      "",
      `Model-assessed confidence: ${debate.summary.confidence}% (not a measured probability).`,
      "",
    );
    list("Strongest case for", debate.summary.strongestPro);
    list("Strongest case against", debate.summary.strongestCon);
    list("Uncertainties", debate.summary.unresolvedUncertainties);
    list("What would change the verdict", debate.summary.whatWouldChangeMind);
  } else if (consensus) {
    const { summary, convergence, holdouts } = consensus.result;
    lines.push(
      "## Finding",
      summary.headline,
      "",
      summary.finding,
      "",
      convergence.finalAnswer,
      "",
      `Stance agreement: ${Math.round(convergence.agreementLevel * 100)}% (not confidence or verification).`,
      "",
    );
    list("Agreed", summary.agreed);
    list("Contested", summary.contested);
    list(
      "Holdouts",
      holdouts.map((entry) => `${entry.agentName}: ${entry.reason}`),
    );
    list("Uncertainties", summary.unresolvedUncertainties);
  } else if (panel) {
    const { chair, advice } = panel.result;
    lines.push(
      "## Chair’s synthesis",
      chair.headline,
      "",
      chair.throughLine,
      "",
      chair.decisionGuidance,
      "",
    );
    for (const entry of advice) {
      lines.push(
        `## ${entry.lensName}`,
        entry.recommendation,
        "",
        entry.reasoning,
        "",
      );
      list("Risks", entry.keyRisks);
      list("Conditions", entry.conditions);
    }
    list(
      "Agreements",
      chair.agreements.map((entry) => entry.point),
    );
    list(
      "Conflicts",
      chair.conflicts.map(
        (entry) =>
          `${entry.point}: ${entry.positions.map((position) => `${position.lensId} — ${position.stance}`).join("; ")}`,
      ),
    );
  }
  if (record.highStakes)
    lines.push("## Topic notice", record.highStakes.message, "");
  if (run.placeholders && Object.keys(run.placeholders).length)
    lines.push(
      "Note: this run contains unavailable or placeholder output. Inspect the original run for details.",
      "",
    );
  list(
    "Sources",
    run.sources.map(
      (source) =>
        `${source.id} · ${source.title} [${source.quality}; ${source.status}]\n  ${source.url}`,
    ),
  );
  lines.push(
    "---",
    "Generated by Polyvise. AI output can be wrong; check the reasoning and sources.",
  );
  return lines.join("\n");
}
